name: Go course CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2
      
      - name: shfmt
        uses: ludeeus/action-shfmt@v2
        with:
          args: "-i 2 -ci -sr"
